[
  {
    id: "55a6a09f-dbc2-4885-bed6-958c21a73d1e",
    idInVersion: "9434179",
    brandId: "8e5f1a6a-9da2-4fe5-bd6b-31be14a06ccf",
    designSystemVersionId: "117328",
    name: "Dark",
    description: "",
    codeName: "dark",
    createdAt: null,
    updatedAt: null,
    overriddenTokens: [
      {
        id: "1edb04d1-32b8-4293-af5d-c22771b7cc02",
        idInVersion: "11803554",
        brandId: "8e5f1a6a-9da2-4fe5-bd6b-31be14a06ccf",
        themeId: "9434179",
        designSystemVersionId: "117328",
        tokenType: "Color",
        origin: null,
        parentGroupId: "1f6141e1-37c2-41b3-8e66-337d35f026f4",
        createdAt: null,
        updatedAt: "2024-07-16T18:55:46.172Z",
        sortOrder: -1,
        properties: [
          {
            idInVersion: "250202",
            id: "5d7eb185-4e39-4ee6-8aad-9b3dfb9c3c50",
            designSystemVersionId: "117328",
            name: "Token set",
            codeName: "tokenSet",
            description: "This token is part of a set",
            propertyType: "Select",
            targetElementType: "Token",
            linkElementType: null,
            options: [
              {
                id: "token-set-core",
                name: "Core",
                backgroundColor: "#F5F2FD",
              },
              {
                id: "token-set-semantic",
                name: "Semantic",
                backgroundColor: "#FEF0F5",
              },
              {
                id: "token-set-component",
                name: "Component",
                backgroundColor: "#CDFDFD",
              },
            ],
          },
        ],
        propertyValues: { tokenSet: "token-set-core" },
        value: {
          color: { r: 232, g: 233, b: 234, referencedTokenId: null },
          opacity: { unit: "Raw", measure: 1, referencedTokenId: null },
          referencedTokenId: null,
        },
        name: "Gray800",
        description: "",
      },
      {
        id: "5786c5fa-bda6-467c-b1ec-c3f2643c5472",
        idInVersion: "11764300",
        brandId: "8e5f1a6a-9da2-4fe5-bd6b-31be14a06ccf",
        themeId: "9434179",
        designSystemVersionId: "117328",
        tokenType: "Color",
        origin: null,
        parentGroupId: "1f6141e1-37c2-41b3-8e66-337d35f026f4",
        createdAt: null,
        updatedAt: "2024-07-16T18:55:25.500Z",
        sortOrder: -1,
        properties: [
          {
            idInVersion: "250202",
            id: "5d7eb185-4e39-4ee6-8aad-9b3dfb9c3c50",
            designSystemVersionId: "117328",
            name: "Token set",
            codeName: "tokenSet",
            description: "This token is part of a set",
            propertyType: "Select",
            targetElementType: "Token",
            linkElementType: null,
            options: [
              {
                id: "token-set-core",
                name: "Core",
                backgroundColor: "#F5F2FD",
              },
              {
                id: "token-set-semantic",
                name: "Semantic",
                backgroundColor: "#FEF0F5",
              },
              {
                id: "token-set-component",
                name: "Component",
                backgroundColor: "#CDFDFD",
              },
            ],
          },
        ],
        propertyValues: { tokenSet: "token-set-core" },
        value: {
          color: { r: 255, g: 255, b: 255, referencedTokenId: null },
          opacity: { unit: "Raw", measure: 1, referencedTokenId: null },
          referencedTokenId: null,
        },
        name: "Gray900",
        description: "",
      },
      {
        id: "613cb58f-498e-4edb-82ff-077289fa89e5",
        idInVersion: "11803558",
        brandId: "8e5f1a6a-9da2-4fe5-bd6b-31be14a06ccf",
        themeId: "9434179",
        designSystemVersionId: "117328",
        tokenType: "Color",
        origin: null,
        parentGroupId: "1f6141e1-37c2-41b3-8e66-337d35f026f4",
        createdAt: null,
        updatedAt: "2024-07-16T18:56:00.498Z",
        sortOrder: -1,
        properties: [
          {
            idInVersion: "250202",
            id: "5d7eb185-4e39-4ee6-8aad-9b3dfb9c3c50",
            designSystemVersionId: "117328",
            name: "Token set",
            codeName: "tokenSet",
            description: "This token is part of a set",
            propertyType: "Select",
            targetElementType: "Token",
            linkElementType: null,
            options: [
              {
                id: "token-set-core",
                name: "Core",
                backgroundColor: "#F5F2FD",
              },
              {
                id: "token-set-semantic",
                name: "Semantic",
                backgroundColor: "#FEF0F5",
              },
              {
                id: "token-set-component",
                name: "Component",
                backgroundColor: "#CDFDFD",
              },
            ],
          },
        ],
        propertyValues: { tokenSet: "token-set-core" },
        value: {
          color: { r: 188, g: 189, b: 191, referencedTokenId: null },
          opacity: { unit: "Raw", measure: 1, referencedTokenId: null },
          referencedTokenId: null,
        },
        name: "Gray700",
        description: "",
      },
      {
        id: "b91767cd-31fe-4ea0-86ca-407b3b566cb6",
        idInVersion: "11803559",
        brandId: "8e5f1a6a-9da2-4fe5-bd6b-31be14a06ccf",
        themeId: "9434179",
        designSystemVersionId: "117328",
        tokenType: "Color",
        origin: null,
        parentGroupId: "1f6141e1-37c2-41b3-8e66-337d35f026f4",
        createdAt: null,
        updatedAt: "2024-07-16T18:56:13.530Z",
        sortOrder: -1,
        properties: [
          {
            idInVersion: "250202",
            id: "5d7eb185-4e39-4ee6-8aad-9b3dfb9c3c50",
            designSystemVersionId: "117328",
            name: "Token set",
            codeName: "tokenSet",
            description: "This token is part of a set",
            propertyType: "Select",
            targetElementType: "Token",
            linkElementType: null,
            options: [
              {
                id: "token-set-core",
                name: "Core",
                backgroundColor: "#F5F2FD",
              },
              {
                id: "token-set-semantic",
                name: "Semantic",
                backgroundColor: "#FEF0F5",
              },
              {
                id: "token-set-component",
                name: "Component",
                backgroundColor: "#CDFDFD",
              },
            ],
          },
        ],
        propertyValues: { tokenSet: "token-set-core" },
        value: {
          color: { r: 152, g: 153, b: 155, referencedTokenId: null },
          opacity: { unit: "Raw", measure: 1, referencedTokenId: null },
          referencedTokenId: null,
        },
        name: "Gray600",
        description: "",
      },
      {
        id: "da6cbe53-9140-4ad2-b0f1-309a9b6e2f31",
        idInVersion: "11803564",
        brandId: "8e5f1a6a-9da2-4fe5-bd6b-31be14a06ccf",
        themeId: "9434179",
        designSystemVersionId: "117328",
        tokenType: "Color",
        origin: null,
        parentGroupId: "1f6141e1-37c2-41b3-8e66-337d35f026f4",
        createdAt: null,
        updatedAt: "2024-07-16T19:00:41.529Z",
        sortOrder: -1,
        properties: [
          {
            idInVersion: "250202",
            id: "5d7eb185-4e39-4ee6-8aad-9b3dfb9c3c50",
            designSystemVersionId: "117328",
            name: "Token set",
            codeName: "tokenSet",
            description: "This token is part of a set",
            propertyType: "Select",
            targetElementType: "Token",
            linkElementType: null,
            options: [
              {
                id: "token-set-core",
                name: "Core",
                backgroundColor: "#F5F2FD",
              },
              {
                id: "token-set-semantic",
                name: "Semantic",
                backgroundColor: "#FEF0F5",
              },
              {
                id: "token-set-component",
                name: "Component",
                backgroundColor: "#CDFDFD",
              },
            ],
          },
        ],
        propertyValues: { tokenSet: "token-set-core" },
        value: {
          color: { r: 81, g: 83, b: 87, referencedTokenId: null },
          opacity: { unit: "Raw", measure: 1, referencedTokenId: null },
          referencedTokenId: null,
        },
        name: "Gray500",
        description: "",
      },
      {
        id: "b027ce26-1f20-42e6-be13-0dc542f01b4b",
        idInVersion: "11803566",
        brandId: "8e5f1a6a-9da2-4fe5-bd6b-31be14a06ccf",
        themeId: "9434179",
        designSystemVersionId: "117328",
        tokenType: "Color",
        origin: null,
        parentGroupId: "1f6141e1-37c2-41b3-8e66-337d35f026f4",
        createdAt: null,
        updatedAt: "2024-07-16T19:00:47.777Z",
        sortOrder: -1,
        properties: [
          {
            idInVersion: "250202",
            id: "5d7eb185-4e39-4ee6-8aad-9b3dfb9c3c50",
            designSystemVersionId: "117328",
            name: "Token set",
            codeName: "tokenSet",
            description: "This token is part of a set",
            propertyType: "Select",
            targetElementType: "Token",
            linkElementType: null,
            options: [
              {
                id: "token-set-core",
                name: "Core",
                backgroundColor: "#F5F2FD",
              },
              {
                id: "token-set-semantic",
                name: "Semantic",
                backgroundColor: "#FEF0F5",
              },
              {
                id: "token-set-component",
                name: "Component",
                backgroundColor: "#CDFDFD",
              },
            ],
          },
        ],
        propertyValues: { tokenSet: "token-set-core" },
        value: {
          color: { r: 45, g: 50, b: 56, referencedTokenId: null },
          opacity: { unit: "Raw", measure: 1, referencedTokenId: null },
          referencedTokenId: null,
        },
        name: "Gray400",
        description: "",
      },
      {
        id: "3b59336f-696f-4ed7-bbb9-77490b02e68a",
        idInVersion: "11803567",
        brandId: "8e5f1a6a-9da2-4fe5-bd6b-31be14a06ccf",
        themeId: "9434179",
        designSystemVersionId: "117328",
        tokenType: "Color",
        origin: null,
        parentGroupId: "1f6141e1-37c2-41b3-8e66-337d35f026f4",
        createdAt: null,
        updatedAt: "2024-07-16T19:00:55.900Z",
        sortOrder: -1,
        properties: [
          {
            idInVersion: "250202",
            id: "5d7eb185-4e39-4ee6-8aad-9b3dfb9c3c50",
            designSystemVersionId: "117328",
            name: "Token set",
            codeName: "tokenSet",
            description: "This token is part of a set",
            propertyType: "Select",
            targetElementType: "Token",
            linkElementType: null,
            options: [
              {
                id: "token-set-core",
                name: "Core",
                backgroundColor: "#F5F2FD",
              },
              {
                id: "token-set-semantic",
                name: "Semantic",
                backgroundColor: "#FEF0F5",
              },
              {
                id: "token-set-component",
                name: "Component",
                backgroundColor: "#CDFDFD",
              },
            ],
          },
        ],
        propertyValues: { tokenSet: "token-set-core" },
        value: {
          color: { r: 34, g: 39, b: 43, referencedTokenId: null },
          opacity: { unit: "Raw", measure: 1, referencedTokenId: null },
          referencedTokenId: null,
        },
        name: "Gray300",
        description: "",
      },
      {
        id: "61311a8d-363a-4b20-9e4e-ead070cd1cd0",
        idInVersion: "11803568",
        brandId: "8e5f1a6a-9da2-4fe5-bd6b-31be14a06ccf",
        themeId: "9434179",
        designSystemVersionId: "117328",
        tokenType: "Color",
        origin: null,
        parentGroupId: "1f6141e1-37c2-41b3-8e66-337d35f026f4",
        createdAt: null,
        updatedAt: "2024-07-16T19:01:02.951Z",
        sortOrder: -1,
        properties: [
          {
            idInVersion: "250202",
            id: "5d7eb185-4e39-4ee6-8aad-9b3dfb9c3c50",
            designSystemVersionId: "117328",
            name: "Token set",
            codeName: "tokenSet",
            description: "This token is part of a set",
            propertyType: "Select",
            targetElementType: "Token",
            linkElementType: null,
            options: [
              {
                id: "token-set-core",
                name: "Core",
                backgroundColor: "#F5F2FD",
              },
              {
                id: "token-set-semantic",
                name: "Semantic",
                backgroundColor: "#FEF0F5",
              },
              {
                id: "token-set-component",
                name: "Component",
                backgroundColor: "#CDFDFD",
              },
            ],
          },
        ],
        propertyValues: { tokenSet: "token-set-core" },
        value: {
          color: { r: 29, g: 33, b: 36, referencedTokenId: null },
          opacity: { unit: "Raw", measure: 1, referencedTokenId: null },
          referencedTokenId: null,
        },
        name: "Gray200",
        description: "",
      },
      {
        id: "1ec975ce-46e1-44fb-b27e-3bd65d010d67",
        idInVersion: "11803569",
        brandId: "8e5f1a6a-9da2-4fe5-bd6b-31be14a06ccf",
        themeId: "9434179",
        designSystemVersionId: "117328",
        tokenType: "Color",
        origin: null,
        parentGroupId: "1f6141e1-37c2-41b3-8e66-337d35f026f4",
        createdAt: null,
        updatedAt: "2024-07-16T19:02:16.804Z",
        sortOrder: -1,
        properties: [
          {
            idInVersion: "250202",
            id: "5d7eb185-4e39-4ee6-8aad-9b3dfb9c3c50",
            designSystemVersionId: "117328",
            name: "Token set",
            codeName: "tokenSet",
            description: "This token is part of a set",
            propertyType: "Select",
            targetElementType: "Token",
            linkElementType: null,
            options: [
              {
                id: "token-set-core",
                name: "Core",
                backgroundColor: "#F5F2FD",
              },
              {
                id: "token-set-semantic",
                name: "Semantic",
                backgroundColor: "#FEF0F5",
              },
              {
                id: "token-set-component",
                name: "Component",
                backgroundColor: "#CDFDFD",
              },
            ],
          },
        ],
        propertyValues: { tokenSet: "token-set-core" },
        value: {
          color: { r: 20, g: 23, b: 25, referencedTokenId: null },
          opacity: { unit: "Raw", measure: 1, referencedTokenId: null },
          referencedTokenId: null,
        },
        name: "Gray100",
        description: "",
      },
      {
        id: "c4289230-727a-4fcd-8186-d0bbf0b8a661",
        idInVersion: "11803574",
        brandId: "8e5f1a6a-9da2-4fe5-bd6b-31be14a06ccf",
        themeId: "9434179",
        designSystemVersionId: "117328",
        tokenType: "Color",
        origin: null,
        parentGroupId: "1f6141e1-37c2-41b3-8e66-337d35f026f4",
        createdAt: null,
        updatedAt: "2024-07-16T19:17:33.107Z",
        sortOrder: -1,
        properties: [
          {
            idInVersion: "250202",
            id: "5d7eb185-4e39-4ee6-8aad-9b3dfb9c3c50",
            designSystemVersionId: "117328",
            name: "Token set",
            codeName: "tokenSet",
            description: "This token is part of a set",
            propertyType: "Select",
            targetElementType: "Token",
            linkElementType: null,
            options: [
              {
                id: "token-set-core",
                name: "Core",
                backgroundColor: "#F5F2FD",
              },
              {
                id: "token-set-semantic",
                name: "Semantic",
                backgroundColor: "#FEF0F5",
              },
              {
                id: "token-set-component",
                name: "Component",
                backgroundColor: "#CDFDFD",
              },
            ],
          },
        ],
        propertyValues: { tokenSet: "token-set-core" },
        value: {
          color: { r: 219, g: 255, b: 241, referencedTokenId: null },
          opacity: { unit: "Raw", measure: 1, referencedTokenId: null },
          referencedTokenId: null,
        },
        name: "Green800",
        description: "",
      },
      {
        id: "8267f25e-f4f7-4d68-96d6-f2dde9167ef7",
        idInVersion: "11803576",
        brandId: "8e5f1a6a-9da2-4fe5-bd6b-31be14a06ccf",
        themeId: "9434179",
        designSystemVersionId: "117328",
        tokenType: "Color",
        origin: null,
        parentGroupId: "1f6141e1-37c2-41b3-8e66-337d35f026f4",
        createdAt: null,
        updatedAt: "2024-07-16T19:18:23.472Z",
        sortOrder: -1,
        properties: [
          {
            idInVersion: "250202",
            id: "5d7eb185-4e39-4ee6-8aad-9b3dfb9c3c50",
            designSystemVersionId: "117328",
            name: "Token set",
            codeName: "tokenSet",
            description: "This token is part of a set",
            propertyType: "Select",
            targetElementType: "Token",
            linkElementType: null,
            options: [
              {
                id: "token-set-core",
                name: "Core",
                backgroundColor: "#F5F2FD",
              },
              {
                id: "token-set-semantic",
                name: "Semantic",
                backgroundColor: "#FEF0F5",
              },
              {
                id: "token-set-component",
                name: "Component",
                backgroundColor: "#CDFDFD",
              },
            ],
          },
        ],
        propertyValues: { tokenSet: "token-set-core" },
        value: {
          color: { r: 134, g: 214, b: 185, referencedTokenId: null },
          opacity: { unit: "Raw", measure: 1, referencedTokenId: null },
          referencedTokenId: null,
        },
        name: "Green700",
        description: "",
      },
      {
        id: "d98499c4-e81a-4390-bf96-d5c7a0f696eb",
        idInVersion: "11803577",
        brandId: "8e5f1a6a-9da2-4fe5-bd6b-31be14a06ccf",
        themeId: "9434179",
        designSystemVersionId: "117328",
        tokenType: "Color",
        origin: null,
        parentGroupId: "1f6141e1-37c2-41b3-8e66-337d35f026f4",
        createdAt: null,
        updatedAt: "2024-07-16T19:20:47.820Z",
        sortOrder: -1,
        properties: [
          {
            idInVersion: "250202",
            id: "5d7eb185-4e39-4ee6-8aad-9b3dfb9c3c50",
            designSystemVersionId: "117328",
            name: "Token set",
            codeName: "tokenSet",
            description: "This token is part of a set",
            propertyType: "Select",
            targetElementType: "Token",
            linkElementType: null,
            options: [
              {
                id: "token-set-core",
                name: "Core",
                backgroundColor: "#F5F2FD",
              },
              {
                id: "token-set-semantic",
                name: "Semantic",
                backgroundColor: "#FEF0F5",
              },
              {
                id: "token-set-component",
                name: "Component",
                backgroundColor: "#CDFDFD",
              },
            ],
          },
        ],
        propertyValues: { tokenSet: "token-set-core" },
        value: {
          color: { r: 66, g: 173, b: 134, referencedTokenId: null },
          opacity: { unit: "Raw", measure: 1, referencedTokenId: null },
          referencedTokenId: null,
        },
        name: "Green600",
        description: "",
      },
      {
        id: "20211c5a-a059-4d1e-8ec7-48434e4508e1",
        idInVersion: "11803578",
        brandId: "8e5f1a6a-9da2-4fe5-bd6b-31be14a06ccf",
        themeId: "9434179",
        designSystemVersionId: "117328",
        tokenType: "Color",
        origin: null,
        parentGroupId: "1f6141e1-37c2-41b3-8e66-337d35f026f4",
        createdAt: null,
        updatedAt: "2024-07-16T19:20:58.314Z",
        sortOrder: -1,
        properties: [
          {
            idInVersion: "250202",
            id: "5d7eb185-4e39-4ee6-8aad-9b3dfb9c3c50",
            designSystemVersionId: "117328",
            name: "Token set",
            codeName: "tokenSet",
            description: "This token is part of a set",
            propertyType: "Select",
            targetElementType: "Token",
            linkElementType: null,
            options: [
              {
                id: "token-set-core",
                name: "Core",
                backgroundColor: "#F5F2FD",
              },
              {
                id: "token-set-semantic",
                name: "Semantic",
                backgroundColor: "#FEF0F5",
              },
              {
                id: "token-set-component",
                name: "Component",
                backgroundColor: "#CDFDFD",
              },
            ],
          },
        ],
        propertyValues: { tokenSet: "token-set-core" },
        value: {
          color: { r: 40, g: 133, b: 99, referencedTokenId: null },
          opacity: { unit: "Raw", measure: 1, referencedTokenId: null },
          referencedTokenId: null,
        },
        name: "Green500",
        description: "",
      },
      {
        id: "f05fe7cf-4728-4bc7-b091-857d815bff90",
        idInVersion: "11803579",
        brandId: "8e5f1a6a-9da2-4fe5-bd6b-31be14a06ccf",
        themeId: "9434179",
        designSystemVersionId: "117328",
        tokenType: "Color",
        origin: null,
        parentGroupId: "1f6141e1-37c2-41b3-8e66-337d35f026f4",
        createdAt: null,
        updatedAt: "2024-07-16T19:21:05.336Z",
        sortOrder: -1,
        properties: [
          {
            idInVersion: "250202",
            id: "5d7eb185-4e39-4ee6-8aad-9b3dfb9c3c50",
            designSystemVersionId: "117328",
            name: "Token set",
            codeName: "tokenSet",
            description: "This token is part of a set",
            propertyType: "Select",
            targetElementType: "Token",
            linkElementType: null,
            options: [
              {
                id: "token-set-core",
                name: "Core",
                backgroundColor: "#F5F2FD",
              },
              {
                id: "token-set-semantic",
                name: "Semantic",
                backgroundColor: "#FEF0F5",
              },
              {
                id: "token-set-component",
                name: "Component",
                backgroundColor: "#CDFDFD",
              },
            ],
          },
        ],
        propertyValues: { tokenSet: "token-set-core" },
        value: {
          color: { r: 32, g: 106, b: 79, referencedTokenId: null },
          opacity: { unit: "Raw", measure: 1, referencedTokenId: null },
          referencedTokenId: null,
        },
        name: "Green400",
        description: "",
      },
      {
        id: "5d343052-282d-4cd4-856f-c98e89860a36",
        idInVersion: "11803580",
        brandId: "8e5f1a6a-9da2-4fe5-bd6b-31be14a06ccf",
        themeId: "9434179",
        designSystemVersionId: "117328",
        tokenType: "Color",
        origin: null,
        parentGroupId: "1f6141e1-37c2-41b3-8e66-337d35f026f4",
        createdAt: null,
        updatedAt: "2024-07-16T19:22:30.002Z",
        sortOrder: -1,
        properties: [
          {
            idInVersion: "250202",
            id: "5d7eb185-4e39-4ee6-8aad-9b3dfb9c3c50",
            designSystemVersionId: "117328",
            name: "Token set",
            codeName: "tokenSet",
            description: "This token is part of a set",
            propertyType: "Select",
            targetElementType: "Token",
            linkElementType: null,
            options: [
              {
                id: "token-set-core",
                name: "Core",
                backgroundColor: "#F5F2FD",
              },
              {
                id: "token-set-semantic",
                name: "Semantic",
                backgroundColor: "#FEF0F5",
              },
              {
                id: "token-set-component",
                name: "Component",
                backgroundColor: "#CDFDFD",
              },
            ],
          },
        ],
        propertyValues: { tokenSet: "token-set-core" },
        value: {
          color: { r: 31, g: 91, b: 69, referencedTokenId: null },
          opacity: { unit: "Raw", measure: 1, referencedTokenId: null },
          referencedTokenId: null,
        },
        name: "Green300",
        description: "",
      },
      {
        id: "019e88fc-4bf7-4042-838d-b92296e68e7c",
        idInVersion: "11803581",
        brandId: "8e5f1a6a-9da2-4fe5-bd6b-31be14a06ccf",
        themeId: "9434179",
        designSystemVersionId: "117328",
        tokenType: "Color",
        origin: null,
        parentGroupId: "1f6141e1-37c2-41b3-8e66-337d35f026f4",
        createdAt: null,
        updatedAt: "2024-07-16T19:21:51.530Z",
        sortOrder: -1,
        properties: [
          {
            idInVersion: "250202",
            id: "5d7eb185-4e39-4ee6-8aad-9b3dfb9c3c50",
            designSystemVersionId: "117328",
            name: "Token set",
            codeName: "tokenSet",
            description: "This token is part of a set",
            propertyType: "Select",
            targetElementType: "Token",
            linkElementType: null,
            options: [
              {
                id: "token-set-core",
                name: "Core",
                backgroundColor: "#F5F2FD",
              },
              {
                id: "token-set-semantic",
                name: "Semantic",
                backgroundColor: "#FEF0F5",
              },
              {
                id: "token-set-component",
                name: "Component",
                backgroundColor: "#CDFDFD",
              },
            ],
          },
        ],
        propertyValues: { tokenSet: "token-set-core" },
        value: {
          color: { r: 18, g: 73, b: 53, referencedTokenId: null },
          opacity: { unit: "Raw", measure: 1, referencedTokenId: null },
          referencedTokenId: null,
        },
        name: "Green200",
        description: "",
      },
      {
        id: "b9116ccc-7257-41de-b958-b876bf6e1a05",
        idInVersion: "11815527",
        brandId: "8e5f1a6a-9da2-4fe5-bd6b-31be14a06ccf",
        themeId: "9434179",
        designSystemVersionId: "117328",
        tokenType: "Color",
        origin: null,
        parentGroupId: "1f6141e1-37c2-41b3-8e66-337d35f026f4",
        createdAt: null,
        updatedAt: "2024-07-17T15:16:18.944Z",
        sortOrder: -1,
        properties: [
          {
            idInVersion: "250202",
            id: "5d7eb185-4e39-4ee6-8aad-9b3dfb9c3c50",
            designSystemVersionId: "117328",
            name: "Token set",
            codeName: "tokenSet",
            description: "This token is part of a set",
            propertyType: "Select",
            targetElementType: "Token",
            linkElementType: null,
            options: [
              {
                id: "token-set-core",
                name: "Core",
                backgroundColor: "#F5F2FD",
              },
              {
                id: "token-set-semantic",
                name: "Semantic",
                backgroundColor: "#FEF0F5",
              },
              {
                id: "token-set-component",
                name: "Component",
                backgroundColor: "#CDFDFD",
              },
            ],
          },
        ],
        propertyValues: { tokenSet: "token-set-semantic" },
        value: {
          color: { r: 152, g: 153, b: 155, referencedTokenId: null },
          opacity: { unit: "Raw", measure: 1, referencedTokenId: null },
          referencedTokenId: "b91767cd-31fe-4ea0-86ca-407b3b566cb6",
        },
        name: "system-background",
        description: "Description for a test semantic token",
      },
    ],
  },
  {
    id: "60a6c28b-9315-410d-aa92-8929eb61c2bd",
    idInVersion: "11803560",
    brandId: "8e5f1a6a-9da2-4fe5-bd6b-31be14a06ccf",
    designSystemVersionId: "117328",
    name: "PWCVD",
    description: "Persons with color vision deficiency ",
    codeName: "pwcvd",
    createdAt: null,
    updatedAt: null,
    overriddenTokens: [
      {
        id: "5786c5fa-bda6-467c-b1ec-c3f2643c5472",
        idInVersion: "11764300",
        brandId: "8e5f1a6a-9da2-4fe5-bd6b-31be14a06ccf",
        themeId: "11803560",
        designSystemVersionId: "117328",
        tokenType: "Color",
        origin: null,
        parentGroupId: "1f6141e1-37c2-41b3-8e66-337d35f026f4",
        createdAt: null,
        updatedAt: "2024-07-16T18:55:25.500Z",
        sortOrder: -1,
        properties: [
          {
            idInVersion: "250202",
            id: "5d7eb185-4e39-4ee6-8aad-9b3dfb9c3c50",
            designSystemVersionId: "117328",
            name: "Token set",
            codeName: "tokenSet",
            description: "This token is part of a set",
            propertyType: "Select",
            targetElementType: "Token",
            linkElementType: null,
            options: [
              {
                id: "token-set-core",
                name: "Core",
                backgroundColor: "#F5F2FD",
              },
              {
                id: "token-set-semantic",
                name: "Semantic",
                backgroundColor: "#FEF0F5",
              },
              {
                id: "token-set-component",
                name: "Component",
                backgroundColor: "#CDFDFD",
              },
            ],
          },
        ],
        propertyValues: { tokenSet: "token-set-core" },
        value: {
          color: { r: 36, g: 36, b: 48, referencedTokenId: null },
          opacity: { unit: "Raw", measure: 1, referencedTokenId: null },
          referencedTokenId: null,
        },
        name: "Gray900",
        description: "",
      },
      {
        id: "1edb04d1-32b8-4293-af5d-c22771b7cc02",
        idInVersion: "11803554",
        brandId: "8e5f1a6a-9da2-4fe5-bd6b-31be14a06ccf",
        themeId: "11803560",
        designSystemVersionId: "117328",
        tokenType: "Color",
        origin: null,
        parentGroupId: "1f6141e1-37c2-41b3-8e66-337d35f026f4",
        createdAt: null,
        updatedAt: "2024-07-16T18:55:46.172Z",
        sortOrder: -1,
        properties: [
          {
            idInVersion: "250202",
            id: "5d7eb185-4e39-4ee6-8aad-9b3dfb9c3c50",
            designSystemVersionId: "117328",
            name: "Token set",
            codeName: "tokenSet",
            description: "This token is part of a set",
            propertyType: "Select",
            targetElementType: "Token",
            linkElementType: null,
            options: [
              {
                id: "token-set-core",
                name: "Core",
                backgroundColor: "#F5F2FD",
              },
              {
                id: "token-set-semantic",
                name: "Semantic",
                backgroundColor: "#FEF0F5",
              },
              {
                id: "token-set-component",
                name: "Component",
                backgroundColor: "#CDFDFD",
              },
            ],
          },
        ],
        propertyValues: { tokenSet: "token-set-core" },
        value: {
          color: { r: 51, g: 51, b: 67, referencedTokenId: null },
          opacity: { unit: "Raw", measure: 1, referencedTokenId: null },
          referencedTokenId: null,
        },
        name: "Gray800",
        description: "",
      },
      {
        id: "613cb58f-498e-4edb-82ff-077289fa89e5",
        idInVersion: "11803558",
        brandId: "8e5f1a6a-9da2-4fe5-bd6b-31be14a06ccf",
        themeId: "11803560",
        designSystemVersionId: "117328",
        tokenType: "Color",
        origin: null,
        parentGroupId: "1f6141e1-37c2-41b3-8e66-337d35f026f4",
        createdAt: null,
        updatedAt: "2024-07-16T18:56:00.498Z",
        sortOrder: -1,
        properties: [
          {
            idInVersion: "250202",
            id: "5d7eb185-4e39-4ee6-8aad-9b3dfb9c3c50",
            designSystemVersionId: "117328",
            name: "Token set",
            codeName: "tokenSet",
            description: "This token is part of a set",
            propertyType: "Select",
            targetElementType: "Token",
            linkElementType: null,
            options: [
              {
                id: "token-set-core",
                name: "Core",
                backgroundColor: "#F5F2FD",
              },
              {
                id: "token-set-semantic",
                name: "Semantic",
                backgroundColor: "#FEF0F5",
              },
              {
                id: "token-set-component",
                name: "Component",
                backgroundColor: "#CDFDFD",
              },
            ],
          },
        ],
        propertyValues: { tokenSet: "token-set-core" },
        value: {
          color: { r: 61, g: 61, b: 87, referencedTokenId: null },
          opacity: { unit: "Raw", measure: 1, referencedTokenId: null },
          referencedTokenId: null,
        },
        name: "Gray700",
        description: "",
      },
      {
        id: "b91767cd-31fe-4ea0-86ca-407b3b566cb6",
        idInVersion: "11803559",
        brandId: "8e5f1a6a-9da2-4fe5-bd6b-31be14a06ccf",
        themeId: "11803560",
        designSystemVersionId: "117328",
        tokenType: "Color",
        origin: null,
        parentGroupId: "1f6141e1-37c2-41b3-8e66-337d35f026f4",
        createdAt: null,
        updatedAt: "2024-07-16T18:56:13.530Z",
        sortOrder: -1,
        properties: [
          {
            idInVersion: "250202",
            id: "5d7eb185-4e39-4ee6-8aad-9b3dfb9c3c50",
            designSystemVersionId: "117328",
            name: "Token set",
            codeName: "tokenSet",
            description: "This token is part of a set",
            propertyType: "Select",
            targetElementType: "Token",
            linkElementType: null,
            options: [
              {
                id: "token-set-core",
                name: "Core",
                backgroundColor: "#F5F2FD",
              },
              {
                id: "token-set-semantic",
                name: "Semantic",
                backgroundColor: "#FEF0F5",
              },
              {
                id: "token-set-component",
                name: "Component",
                backgroundColor: "#CDFDFD",
              },
            ],
          },
        ],
        propertyValues: { tokenSet: "token-set-core" },
        value: {
          color: { r: 79, g: 79, b: 106, referencedTokenId: null },
          opacity: { unit: "Raw", measure: 1, referencedTokenId: null },
          referencedTokenId: null,
        },
        name: "Gray600",
        description: "",
      },
      {
        id: "da6cbe53-9140-4ad2-b0f1-309a9b6e2f31",
        idInVersion: "11803564",
        brandId: "8e5f1a6a-9da2-4fe5-bd6b-31be14a06ccf",
        themeId: "11803560",
        designSystemVersionId: "117328",
        tokenType: "Color",
        origin: null,
        parentGroupId: "1f6141e1-37c2-41b3-8e66-337d35f026f4",
        createdAt: null,
        updatedAt: "2024-07-16T19:00:41.529Z",
        sortOrder: -1,
        properties: [
          {
            idInVersion: "250202",
            id: "5d7eb185-4e39-4ee6-8aad-9b3dfb9c3c50",
            designSystemVersionId: "117328",
            name: "Token set",
            codeName: "tokenSet",
            description: "This token is part of a set",
            propertyType: "Select",
            targetElementType: "Token",
            linkElementType: null,
            options: [
              {
                id: "token-set-core",
                name: "Core",
                backgroundColor: "#F5F2FD",
              },
              {
                id: "token-set-semantic",
                name: "Semantic",
                backgroundColor: "#FEF0F5",
              },
              {
                id: "token-set-component",
                name: "Component",
                backgroundColor: "#CDFDFD",
              },
            ],
          },
        ],
        propertyValues: { tokenSet: "token-set-core" },
        value: {
          color: { r: 97, g: 97, b: 126, referencedTokenId: null },
          opacity: { unit: "Raw", measure: 1, referencedTokenId: null },
          referencedTokenId: null,
        },
        name: "Gray500",
        description: "",
      },
      {
        id: "b027ce26-1f20-42e6-be13-0dc542f01b4b",
        idInVersion: "11803566",
        brandId: "8e5f1a6a-9da2-4fe5-bd6b-31be14a06ccf",
        themeId: "11803560",
        designSystemVersionId: "117328",
        tokenType: "Color",
        origin: null,
        parentGroupId: "1f6141e1-37c2-41b3-8e66-337d35f026f4",
        createdAt: null,
        updatedAt: "2024-07-16T19:00:47.777Z",
        sortOrder: -1,
        properties: [
          {
            idInVersion: "250202",
            id: "5d7eb185-4e39-4ee6-8aad-9b3dfb9c3c50",
            designSystemVersionId: "117328",
            name: "Token set",
            codeName: "tokenSet",
            description: "This token is part of a set",
            propertyType: "Select",
            targetElementType: "Token",
            linkElementType: null,
            options: [
              {
                id: "token-set-core",
                name: "Core",
                backgroundColor: "#F5F2FD",
              },
              {
                id: "token-set-semantic",
                name: "Semantic",
                backgroundColor: "#FEF0F5",
              },
              {
                id: "token-set-component",
                name: "Component",
                backgroundColor: "#CDFDFD",
              },
            ],
          },
        ],
        propertyValues: { tokenSet: "token-set-core" },
        value: {
          color: { r: 204, g: 204, b: 220, referencedTokenId: null },
          opacity: { unit: "Raw", measure: 1, referencedTokenId: null },
          referencedTokenId: null,
        },
        name: "Gray400",
        description: "",
      },
      {
        id: "3b59336f-696f-4ed7-bbb9-77490b02e68a",
        idInVersion: "11803567",
        brandId: "8e5f1a6a-9da2-4fe5-bd6b-31be14a06ccf",
        themeId: "11803560",
        designSystemVersionId: "117328",
        tokenType: "Color",
        origin: null,
        parentGroupId: "1f6141e1-37c2-41b3-8e66-337d35f026f4",
        createdAt: null,
        updatedAt: "2024-07-16T19:00:55.900Z",
        sortOrder: -1,
        properties: [
          {
            idInVersion: "250202",
            id: "5d7eb185-4e39-4ee6-8aad-9b3dfb9c3c50",
            designSystemVersionId: "117328",
            name: "Token set",
            codeName: "tokenSet",
            description: "This token is part of a set",
            propertyType: "Select",
            targetElementType: "Token",
            linkElementType: null,
            options: [
              {
                id: "token-set-core",
                name: "Core",
                backgroundColor: "#F5F2FD",
              },
              {
                id: "token-set-semantic",
                name: "Semantic",
                backgroundColor: "#FEF0F5",
              },
              {
                id: "token-set-component",
                name: "Component",
                backgroundColor: "#CDFDFD",
              },
            ],
          },
        ],
        propertyValues: { tokenSet: "token-set-core" },
        value: {
          color: { r: 233, g: 233, b: 243, referencedTokenId: null },
          opacity: { unit: "Raw", measure: 1, referencedTokenId: null },
          referencedTokenId: null,
        },
        name: "Gray300",
        description: "",
      },
      {
        id: "61311a8d-363a-4b20-9e4e-ead070cd1cd0",
        idInVersion: "11803568",
        brandId: "8e5f1a6a-9da2-4fe5-bd6b-31be14a06ccf",
        themeId: "11803560",
        designSystemVersionId: "117328",
        tokenType: "Color",
        origin: null,
        parentGroupId: "1f6141e1-37c2-41b3-8e66-337d35f026f4",
        createdAt: null,
        updatedAt: "2024-07-16T19:01:02.951Z",
        sortOrder: -1,
        properties: [
          {
            idInVersion: "250202",
            id: "5d7eb185-4e39-4ee6-8aad-9b3dfb9c3c50",
            designSystemVersionId: "117328",
            name: "Token set",
            codeName: "tokenSet",
            description: "This token is part of a set",
            propertyType: "Select",
            targetElementType: "Token",
            linkElementType: null,
            options: [
              {
                id: "token-set-core",
                name: "Core",
                backgroundColor: "#F5F2FD",
              },
              {
                id: "token-set-semantic",
                name: "Semantic",
                backgroundColor: "#FEF0F5",
              },
              {
                id: "token-set-component",
                name: "Component",
                backgroundColor: "#CDFDFD",
              },
            ],
          },
        ],
        propertyValues: { tokenSet: "token-set-core" },
        value: {
          color: { r: 245, g: 245, b: 249, referencedTokenId: null },
          opacity: { unit: "Raw", measure: 1, referencedTokenId: null },
          referencedTokenId: null,
        },
        name: "Gray200",
        description: "",
      },
      {
        id: "1ec975ce-46e1-44fb-b27e-3bd65d010d67",
        idInVersion: "11803569",
        brandId: "8e5f1a6a-9da2-4fe5-bd6b-31be14a06ccf",
        themeId: "11803560",
        designSystemVersionId: "117328",
        tokenType: "Color",
        origin: null,
        parentGroupId: "1f6141e1-37c2-41b3-8e66-337d35f026f4",
        createdAt: null,
        updatedAt: "2024-07-16T19:02:16.804Z",
        sortOrder: -1,
        properties: [
          {
            idInVersion: "250202",
            id: "5d7eb185-4e39-4ee6-8aad-9b3dfb9c3c50",
            designSystemVersionId: "117328",
            name: "Token set",
            codeName: "tokenSet",
            description: "This token is part of a set",
            propertyType: "Select",
            targetElementType: "Token",
            linkElementType: null,
            options: [
              {
                id: "token-set-core",
                name: "Core",
                backgroundColor: "#F5F2FD",
              },
              {
                id: "token-set-semantic",
                name: "Semantic",
                backgroundColor: "#FEF0F5",
              },
              {
                id: "token-set-component",
                name: "Component",
                backgroundColor: "#CDFDFD",
              },
            ],
          },
        ],
        propertyValues: { tokenSet: "token-set-core" },
        value: {
          color: { r: 252, g: 252, b: 254, referencedTokenId: null },
          opacity: { unit: "Raw", measure: 1, referencedTokenId: null },
          referencedTokenId: null,
        },
        name: "Gray100",
        description: "",
      },
      {
        id: "99439379-6966-4659-b205-c2ac23f74c1d",
        idInVersion: "11803573",
        brandId: "8e5f1a6a-9da2-4fe5-bd6b-31be14a06ccf",
        themeId: "11803560",
        designSystemVersionId: "117328",
        tokenType: "Color",
        origin: null,
        parentGroupId: "1f6141e1-37c2-41b3-8e66-337d35f026f4",
        createdAt: null,
        updatedAt: "2024-07-16T19:12:25.430Z",
        sortOrder: -1,
        properties: [
          {
            idInVersion: "250202",
            id: "5d7eb185-4e39-4ee6-8aad-9b3dfb9c3c50",
            designSystemVersionId: "117328",
            name: "Token set",
            codeName: "tokenSet",
            description: "This token is part of a set",
            propertyType: "Select",
            targetElementType: "Token",
            linkElementType: null,
            options: [
              {
                id: "token-set-core",
                name: "Core",
                backgroundColor: "#F5F2FD",
              },
              {
                id: "token-set-semantic",
                name: "Semantic",
                backgroundColor: "#FEF0F5",
              },
              {
                id: "token-set-component",
                name: "Component",
                backgroundColor: "#CDFDFD",
              },
            ],
          },
        ],
        propertyValues: { tokenSet: "token-set-core" },
        value: {
          color: { r: 34, g: 35, b: 43, referencedTokenId: null },
          opacity: { unit: "Raw", measure: 1, referencedTokenId: null },
          referencedTokenId: null,
        },
        name: "Green900",
        description: "",
      },
      {
        id: "c4289230-727a-4fcd-8186-d0bbf0b8a661",
        idInVersion: "11803574",
        brandId: "8e5f1a6a-9da2-4fe5-bd6b-31be14a06ccf",
        themeId: "11803560",
        designSystemVersionId: "117328",
        tokenType: "Color",
        origin: null,
        parentGroupId: "1f6141e1-37c2-41b3-8e66-337d35f026f4",
        createdAt: null,
        updatedAt: "2024-07-16T19:17:33.107Z",
        sortOrder: -1,
        properties: [
          {
            idInVersion: "250202",
            id: "5d7eb185-4e39-4ee6-8aad-9b3dfb9c3c50",
            designSystemVersionId: "117328",
            name: "Token set",
            codeName: "tokenSet",
            description: "This token is part of a set",
            propertyType: "Select",
            targetElementType: "Token",
            linkElementType: null,
            options: [
              {
                id: "token-set-core",
                name: "Core",
                backgroundColor: "#F5F2FD",
              },
              {
                id: "token-set-semantic",
                name: "Semantic",
                backgroundColor: "#FEF0F5",
              },
              {
                id: "token-set-component",
                name: "Component",
                backgroundColor: "#CDFDFD",
              },
            ],
          },
        ],
        propertyValues: { tokenSet: "token-set-core" },
        value: {
          color: { r: 53, g: 53, b: 60, referencedTokenId: null },
          opacity: { unit: "Raw", measure: 1, referencedTokenId: null },
          referencedTokenId: null,
        },
        name: "Green800",
        description: "",
      },
      {
        id: "8267f25e-f4f7-4d68-96d6-f2dde9167ef7",
        idInVersion: "11803576",
        brandId: "8e5f1a6a-9da2-4fe5-bd6b-31be14a06ccf",
        themeId: "11803560",
        designSystemVersionId: "117328",
        tokenType: "Color",
        origin: null,
        parentGroupId: "1f6141e1-37c2-41b3-8e66-337d35f026f4",
        createdAt: null,
        updatedAt: "2024-07-16T19:18:23.472Z",
        sortOrder: -1,
        properties: [
          {
            idInVersion: "250202",
            id: "5d7eb185-4e39-4ee6-8aad-9b3dfb9c3c50",
            designSystemVersionId: "117328",
            name: "Token set",
            codeName: "tokenSet",
            description: "This token is part of a set",
            propertyType: "Select",
            targetElementType: "Token",
            linkElementType: null,
            options: [
              {
                id: "token-set-core",
                name: "Core",
                backgroundColor: "#F5F2FD",
              },
              {
                id: "token-set-semantic",
                name: "Semantic",
                backgroundColor: "#FEF0F5",
              },
              {
                id: "token-set-component",
                name: "Component",
                backgroundColor: "#CDFDFD",
              },
            ],
          },
        ],
        propertyValues: { tokenSet: "token-set-core" },
        value: {
          color: { r: 62, g: 63, b: 73, referencedTokenId: null },
          opacity: { unit: "Raw", measure: 1, referencedTokenId: null },
          referencedTokenId: null,
        },
        name: "Green700",
        description: "",
      },
      {
        id: "d98499c4-e81a-4390-bf96-d5c7a0f696eb",
        idInVersion: "11803577",
        brandId: "8e5f1a6a-9da2-4fe5-bd6b-31be14a06ccf",
        themeId: "11803560",
        designSystemVersionId: "117328",
        tokenType: "Color",
        origin: null,
        parentGroupId: "1f6141e1-37c2-41b3-8e66-337d35f026f4",
        createdAt: null,
        updatedAt: "2024-07-16T19:20:47.820Z",
        sortOrder: -1,
        properties: [
          {
            idInVersion: "250202",
            id: "5d7eb185-4e39-4ee6-8aad-9b3dfb9c3c50",
            designSystemVersionId: "117328",
            name: "Token set",
            codeName: "tokenSet",
            description: "This token is part of a set",
            propertyType: "Select",
            targetElementType: "Token",
            linkElementType: null,
            options: [
              {
                id: "token-set-core",
                name: "Core",
                backgroundColor: "#F5F2FD",
              },
              {
                id: "token-set-semantic",
                name: "Semantic",
                backgroundColor: "#FEF0F5",
              },
              {
                id: "token-set-component",
                name: "Component",
                backgroundColor: "#CDFDFD",
              },
            ],
          },
        ],
        propertyValues: { tokenSet: "token-set-core" },
        value: {
          color: { r: 77, g: 78, b: 91, referencedTokenId: null },
          opacity: { unit: "Raw", measure: 1, referencedTokenId: null },
          referencedTokenId: null,
        },
        name: "Green600",
        description: "",
      },
      {
        id: "20211c5a-a059-4d1e-8ec7-48434e4508e1",
        idInVersion: "11803578",
        brandId: "8e5f1a6a-9da2-4fe5-bd6b-31be14a06ccf",
        themeId: "11803560",
        designSystemVersionId: "117328",
        tokenType: "Color",
        origin: null,
        parentGroupId: "1f6141e1-37c2-41b3-8e66-337d35f026f4",
        createdAt: null,
        updatedAt: "2024-07-16T19:20:58.314Z",
        sortOrder: -1,
        properties: [
          {
            idInVersion: "250202",
            id: "5d7eb185-4e39-4ee6-8aad-9b3dfb9c3c50",
            designSystemVersionId: "117328",
            name: "Token set",
            codeName: "tokenSet",
            description: "This token is part of a set",
            propertyType: "Select",
            targetElementType: "Token",
            linkElementType: null,
            options: [
              {
                id: "token-set-core",
                name: "Core",
                backgroundColor: "#F5F2FD",
              },
              {
                id: "token-set-semantic",
                name: "Semantic",
                backgroundColor: "#FEF0F5",
              },
              {
                id: "token-set-component",
                name: "Component",
                backgroundColor: "#CDFDFD",
              },
            ],
          },
        ],
        propertyValues: { tokenSet: "token-set-core" },
        value: {
          color: { r: 152, g: 152, b: 160, referencedTokenId: null },
          opacity: { unit: "Raw", measure: 1, referencedTokenId: null },
          referencedTokenId: null,
        },
        name: "Green500",
        description: "",
      },
      {
        id: "f05fe7cf-4728-4bc7-b091-857d815bff90",
        idInVersion: "11803579",
        brandId: "8e5f1a6a-9da2-4fe5-bd6b-31be14a06ccf",
        themeId: "11803560",
        designSystemVersionId: "117328",
        tokenType: "Color",
        origin: null,
        parentGroupId: "1f6141e1-37c2-41b3-8e66-337d35f026f4",
        createdAt: null,
        updatedAt: "2024-07-16T19:21:05.336Z",
        sortOrder: -1,
        properties: [
          {
            idInVersion: "250202",
            id: "5d7eb185-4e39-4ee6-8aad-9b3dfb9c3c50",
            designSystemVersionId: "117328",
            name: "Token set",
            codeName: "tokenSet",
            description: "This token is part of a set",
            propertyType: "Select",
            targetElementType: "Token",
            linkElementType: null,
            options: [
              {
                id: "token-set-core",
                name: "Core",
                backgroundColor: "#F5F2FD",
              },
              {
                id: "token-set-semantic",
                name: "Semantic",
                backgroundColor: "#FEF0F5",
              },
              {
                id: "token-set-component",
                name: "Component",
                backgroundColor: "#CDFDFD",
              },
            ],
          },
        ],
        propertyValues: { tokenSet: "token-set-core" },
        value: {
          color: { r: 192, g: 193, b: 197, referencedTokenId: null },
          opacity: { unit: "Raw", measure: 1, referencedTokenId: null },
          referencedTokenId: null,
        },
        name: "Green400",
        description: "",
      },
      {
        id: "5d343052-282d-4cd4-856f-c98e89860a36",
        idInVersion: "11803580",
        brandId: "8e5f1a6a-9da2-4fe5-bd6b-31be14a06ccf",
        themeId: "11803560",
        designSystemVersionId: "117328",
        tokenType: "Color",
        origin: null,
        parentGroupId: "1f6141e1-37c2-41b3-8e66-337d35f026f4",
        createdAt: null,
        updatedAt: "2024-07-16T19:22:30.002Z",
        sortOrder: -1,
        properties: [
          {
            idInVersion: "250202",
            id: "5d7eb185-4e39-4ee6-8aad-9b3dfb9c3c50",
            designSystemVersionId: "117328",
            name: "Token set",
            codeName: "tokenSet",
            description: "This token is part of a set",
            propertyType: "Select",
            targetElementType: "Token",
            linkElementType: null,
            options: [
              {
                id: "token-set-core",
                name: "Core",
                backgroundColor: "#F5F2FD",
              },
              {
                id: "token-set-semantic",
                name: "Semantic",
                backgroundColor: "#FEF0F5",
              },
              {
                id: "token-set-component",
                name: "Component",
                backgroundColor: "#CDFDFD",
              },
            ],
          },
        ],
        propertyValues: { tokenSet: "token-set-core" },
        value: {
          color: { r: 215, g: 215, b: 218, referencedTokenId: null },
          opacity: { unit: "Raw", measure: 1, referencedTokenId: null },
          referencedTokenId: null,
        },
        name: "Green300",
        description: "",
      },
      {
        id: "019e88fc-4bf7-4042-838d-b92296e68e7c",
        idInVersion: "11803581",
        brandId: "8e5f1a6a-9da2-4fe5-bd6b-31be14a06ccf",
        themeId: "11803560",
        designSystemVersionId: "117328",
        tokenType: "Color",
        origin: null,
        parentGroupId: "1f6141e1-37c2-41b3-8e66-337d35f026f4",
        createdAt: null,
        updatedAt: "2024-07-16T19:21:51.530Z",
        sortOrder: -1,
        properties: [
          {
            idInVersion: "250202",
            id: "5d7eb185-4e39-4ee6-8aad-9b3dfb9c3c50",
            designSystemVersionId: "117328",
            name: "Token set",
            codeName: "tokenSet",
            description: "This token is part of a set",
            propertyType: "Select",
            targetElementType: "Token",
            linkElementType: null,
            options: [
              {
                id: "token-set-core",
                name: "Core",
                backgroundColor: "#F5F2FD",
              },
              {
                id: "token-set-semantic",
                name: "Semantic",
                backgroundColor: "#FEF0F5",
              },
              {
                id: "token-set-component",
                name: "Component",
                backgroundColor: "#CDFDFD",
              },
            ],
          },
        ],
        propertyValues: { tokenSet: "token-set-core" },
        value: {
          color: { r: 238, g: 238, b: 239, referencedTokenId: null },
          opacity: { unit: "Raw", measure: 1, referencedTokenId: null },
          referencedTokenId: null,
        },
        name: "Green200",
        description: "",
      },
      {
        id: "36ca0f2d-90ec-4b04-a738-2dd6f9653530",
        idInVersion: "11803582",
        brandId: "8e5f1a6a-9da2-4fe5-bd6b-31be14a06ccf",
        themeId: "11803560",
        designSystemVersionId: "117328",
        tokenType: "Color",
        origin: null,
        parentGroupId: "1f6141e1-37c2-41b3-8e66-337d35f026f4",
        createdAt: null,
        updatedAt: "2024-07-16T19:22:38.372Z",
        sortOrder: -1,
        properties: [
          {
            idInVersion: "250202",
            id: "5d7eb185-4e39-4ee6-8aad-9b3dfb9c3c50",
            designSystemVersionId: "117328",
            name: "Token set",
            codeName: "tokenSet",
            description: "This token is part of a set",
            propertyType: "Select",
            targetElementType: "Token",
            linkElementType: null,
            options: [
              {
                id: "token-set-core",
                name: "Core",
                backgroundColor: "#F5F2FD",
              },
              {
                id: "token-set-semantic",
                name: "Semantic",
                backgroundColor: "#FEF0F5",
              },
              {
                id: "token-set-component",
                name: "Component",
                backgroundColor: "#CDFDFD",
              },
            ],
          },
        ],
        propertyValues: { tokenSet: "token-set-core" },
        value: {
          color: { r: 252, g: 252, b: 252, referencedTokenId: null },
          opacity: { unit: "Raw", measure: 1, referencedTokenId: null },
          referencedTokenId: null,
        },
        name: "Green100",
        description: "",
      },
    ],
  },
];
