const typo = [
  {
    id: "c90adb28-121e-4d01-aa22-cf96f9ef07e7",
    idInVersion: "12042261",
    brandId: "8e5f1a6a-9da2-4fe5-bd6b-31be14a06ccf",
    themeId: null,
    designSystemVersionId: "117328",
    name: "H1",
    description: "",
    tokenType: "Typography",
    origin: null,
    parentGroupId: "fbdb2c61-c9f0-471d-ac34-dcafe4e5b21f",
    createdAt: null,
    updatedAt: "2024-07-29T15:38:42.432Z",
    sortOrder: -1,
    properties: [
      {
        idInVersion: "250202",
        id: "5d7eb185-4e39-4ee6-8aad-9b3dfb9c3c50",
        designSystemVersionId: "117328",
        name: "Token set",
        codeName: "tokenSet",
        description: "This token is part of a set",
        propertyType: "Select",
        targetElementType: "Token",
        linkElementType: null,
        options: [
          { id: "token-set-core", name: "Core", backgroundColor: "#F5F2FD" },
          {
            id: "token-set-semantic",
            name: "Semantic",
            backgroundColor: "#FEF0F5",
          },
          {
            id: "token-set-component",
            name: "Component",
            backgroundColor: "#CDFDFD",
          },
        ],
      },
    ],
    propertyValues: { tokenSet: "token-set-core" },
    value: {
      fontFamily: {
        text: "Mulish",
        referencedTokenId: "e8435484-951d-41ea-9a5f-11fbe657e6e9",
      },
      fontWeight: {
        text: "Bold",
        referencedTokenId: "fda6feb1-e60c-4cdd-a7b1-0485326eff4c",
      },
      fontSize: {
        unit: "Pixels",
        measure: 39,
        referencedTokenId: "ad20ab7a-3404-4180-a423-1e93c0abfc2f",
      },
      textDecoration: { value: "None", referencedTokenId: null },
      textCase: { value: "Original", referencedTokenId: null },
      letterSpacing: { unit: "Pixels", measure: 0, referencedTokenId: null },
      lineHeight: {
        unit: "Pixels",
        measure: 48,
        referencedTokenId: "65b53b3b-1ab9-42d6-86c6-11506085a357",
      },
      paragraphIndent: { unit: "Pixels", measure: 0, referencedTokenId: null },
      paragraphSpacing: { unit: "Pixels", measure: 0, referencedTokenId: null },
      referencedTokenId: null,
    },
  },
  {
    id: "5d43cc43-c148-4b3e-a957-4f763283e104",
    idInVersion: "12042308",
    brandId: "8e5f1a6a-9da2-4fe5-bd6b-31be14a06ccf",
    themeId: null,
    designSystemVersionId: "117328",
    name: "H2",
    description: "",
    tokenType: "Typography",
    origin: null,
    parentGroupId: "fbdb2c61-c9f0-471d-ac34-dcafe4e5b21f",
    createdAt: null,
    updatedAt: "2024-07-29T15:38:42.437Z",
    sortOrder: -1,
    properties: [
      {
        idInVersion: "250202",
        id: "5d7eb185-4e39-4ee6-8aad-9b3dfb9c3c50",
        designSystemVersionId: "117328",
        name: "Token set",
        codeName: "tokenSet",
        description: "This token is part of a set",
        propertyType: "Select",
        targetElementType: "Token",
        linkElementType: null,
        options: [
          { id: "token-set-core", name: "Core", backgroundColor: "#F5F2FD" },
          {
            id: "token-set-semantic",
            name: "Semantic",
            backgroundColor: "#FEF0F5",
          },
          {
            id: "token-set-component",
            name: "Component",
            backgroundColor: "#CDFDFD",
          },
        ],
      },
    ],
    propertyValues: { tokenSet: "token-set-core" },
    value: {
      fontFamily: {
        text: "Besley",
        referencedTokenId: "bc8e54b6-fdb1-4d1e-9283-33b00fd3051a",
      },
      fontWeight: {
        text: "Medium",
        referencedTokenId: "a4145898-3eca-449e-aa61-a4ccdfe4482f",
      },
      fontSize: {
        unit: "Pixels",
        measure: 31,
        referencedTokenId: "b75e3784-8d33-4786-a887-f09e3e271077",
      },
      textDecoration: { value: "None", referencedTokenId: null },
      textCase: { value: "Original", referencedTokenId: null },
      letterSpacing: { unit: "Pixels", measure: 0, referencedTokenId: null },
      lineHeight: {
        unit: "Pixels",
        measure: 40,
        referencedTokenId: "cdc385d3-8bdc-4001-94c0-eee3a400dc71",
      },
      paragraphIndent: { unit: "Pixels", measure: 0, referencedTokenId: null },
      paragraphSpacing: { unit: "Pixels", measure: 0, referencedTokenId: null },
      referencedTokenId: null,
    },
  },
  {
    id: "aa4b34d8-d2e7-4383-a686-39f807cae2af",
    idInVersion: "12042310",
    brandId: "8e5f1a6a-9da2-4fe5-bd6b-31be14a06ccf",
    themeId: null,
    designSystemVersionId: "117328",
    name: "H3",
    description: "",
    tokenType: "Typography",
    origin: null,
    parentGroupId: "fbdb2c61-c9f0-471d-ac34-dcafe4e5b21f",
    createdAt: null,
    updatedAt: "2024-07-29T15:38:42.441Z",
    sortOrder: -1,
    properties: [
      {
        idInVersion: "250202",
        id: "5d7eb185-4e39-4ee6-8aad-9b3dfb9c3c50",
        designSystemVersionId: "117328",
        name: "Token set",
        codeName: "tokenSet",
        description: "This token is part of a set",
        propertyType: "Select",
        targetElementType: "Token",
        linkElementType: null,
        options: [
          { id: "token-set-core", name: "Core", backgroundColor: "#F5F2FD" },
          {
            id: "token-set-semantic",
            name: "Semantic",
            backgroundColor: "#FEF0F5",
          },
          {
            id: "token-set-component",
            name: "Component",
            backgroundColor: "#CDFDFD",
          },
        ],
      },
    ],
    propertyValues: { tokenSet: "token-set-core" },
    value: {
      fontFamily: {
        text: "Besley",
        referencedTokenId: "bc8e54b6-fdb1-4d1e-9283-33b00fd3051a",
      },
      fontWeight: {
        text: "Medium",
        referencedTokenId: "a4145898-3eca-449e-aa61-a4ccdfe4482f",
      },
      fontSize: {
        unit: "Pixels",
        measure: 25,
        referencedTokenId: "a7bf7725-eaa3-4bc4-ae9b-ccaef4094f19",
      },
      textDecoration: { value: "None", referencedTokenId: null },
      textCase: { value: "Original", referencedTokenId: null },
      letterSpacing: { unit: "Pixels", measure: 0, referencedTokenId: null },
      lineHeight: {
        unit: "Pixels",
        measure: 32,
        referencedTokenId: "0bbc942e-0097-4b06-bd3f-c6dff332d693",
      },
      paragraphIndent: { unit: "Pixels", measure: 0, referencedTokenId: null },
      paragraphSpacing: { unit: "Pixels", measure: 0, referencedTokenId: null },
      referencedTokenId: null,
    },
  },
  {
    id: "d7415b80-1bcc-4dfb-9fd2-d1a0bc8ffa79",
    idInVersion: "12042311",
    brandId: "8e5f1a6a-9da2-4fe5-bd6b-31be14a06ccf",
    themeId: null,
    designSystemVersionId: "117328",
    name: "H4",
    description: "",
    tokenType: "Typography",
    origin: null,
    parentGroupId: "fbdb2c61-c9f0-471d-ac34-dcafe4e5b21f",
    createdAt: null,
    updatedAt: "2024-07-29T15:38:42.445Z",
    sortOrder: -1,
    properties: [
      {
        idInVersion: "250202",
        id: "5d7eb185-4e39-4ee6-8aad-9b3dfb9c3c50",
        designSystemVersionId: "117328",
        name: "Token set",
        codeName: "tokenSet",
        description: "This token is part of a set",
        propertyType: "Select",
        targetElementType: "Token",
        linkElementType: null,
        options: [
          { id: "token-set-core", name: "Core", backgroundColor: "#F5F2FD" },
          {
            id: "token-set-semantic",
            name: "Semantic",
            backgroundColor: "#FEF0F5",
          },
          {
            id: "token-set-component",
            name: "Component",
            backgroundColor: "#CDFDFD",
          },
        ],
      },
    ],
    propertyValues: { tokenSet: "token-set-core" },
    value: {
      fontFamily: {
        text: "Mulish",
        referencedTokenId: "e8435484-951d-41ea-9a5f-11fbe657e6e9",
      },
      fontWeight: {
        text: "SemiBold",
        referencedTokenId: "e49ffd95-9092-41be-9579-7a3fe8248b4d",
      },
      fontSize: {
        unit: "Pixels",
        measure: 20,
        referencedTokenId: "5fed8aad-58e6-4b8f-8016-5110f285af1d",
      },
      textDecoration: { value: "None", referencedTokenId: null },
      textCase: { value: "Original", referencedTokenId: null },
      letterSpacing: { unit: "Pixels", measure: 0, referencedTokenId: null },
      lineHeight: {
        unit: "Pixels",
        measure: 28,
        referencedTokenId: "b4338ea6-826f-4406-a70d-6bea3d3c9a23",
      },
      paragraphIndent: { unit: "Pixels", measure: 0, referencedTokenId: null },
      paragraphSpacing: { unit: "Pixels", measure: 0, referencedTokenId: null },
      referencedTokenId: null,
    },
  },
  {
    id: "8d8410dc-663d-4baf-8849-5502202a677d",
    idInVersion: "12042312",
    brandId: "8e5f1a6a-9da2-4fe5-bd6b-31be14a06ccf",
    themeId: null,
    designSystemVersionId: "117328",
    name: "H5",
    description: "",
    tokenType: "Typography",
    origin: null,
    parentGroupId: "fbdb2c61-c9f0-471d-ac34-dcafe4e5b21f",
    createdAt: null,
    updatedAt: "2024-07-29T15:38:42.449Z",
    sortOrder: -1,
    properties: [
      {
        idInVersion: "250202",
        id: "5d7eb185-4e39-4ee6-8aad-9b3dfb9c3c50",
        designSystemVersionId: "117328",
        name: "Token set",
        codeName: "tokenSet",
        description: "This token is part of a set",
        propertyType: "Select",
        targetElementType: "Token",
        linkElementType: null,
        options: [
          { id: "token-set-core", name: "Core", backgroundColor: "#F5F2FD" },
          {
            id: "token-set-semantic",
            name: "Semantic",
            backgroundColor: "#FEF0F5",
          },
          {
            id: "token-set-component",
            name: "Component",
            backgroundColor: "#CDFDFD",
          },
        ],
      },
    ],
    propertyValues: { tokenSet: "token-set-core" },
    value: {
      fontFamily: {
        text: "Mulish",
        referencedTokenId: "e8435484-951d-41ea-9a5f-11fbe657e6e9",
      },
      fontWeight: {
        text: "Bold",
        referencedTokenId: "fda6feb1-e60c-4cdd-a7b1-0485326eff4c",
      },
      fontSize: {
        unit: "Pixels",
        measure: 16,
        referencedTokenId: "e92bfa56-82cf-425d-8cbc-9343d6937c42",
      },
      textDecoration: { value: "None", referencedTokenId: null },
      textCase: { value: "Original", referencedTokenId: null },
      letterSpacing: { unit: "Pixels", measure: 0, referencedTokenId: null },
      lineHeight: {
        unit: "Pixels",
        measure: 20,
        referencedTokenId: "8a29497e-c831-454a-be11-ae4632c8867b",
      },
      paragraphIndent: { unit: "Pixels", measure: 0, referencedTokenId: null },
      paragraphSpacing: { unit: "Pixels", measure: 0, referencedTokenId: null },
      referencedTokenId: null,
    },
  },
  {
    id: "9f9384f9-32a4-4377-8129-0a573a8bdcd8",
    idInVersion: "12042314",
    brandId: "8e5f1a6a-9da2-4fe5-bd6b-31be14a06ccf",
    themeId: null,
    designSystemVersionId: "117328",
    name: "Body",
    description: "",
    tokenType: "Typography",
    origin: null,
    parentGroupId: "fbdb2c61-c9f0-471d-ac34-dcafe4e5b21f",
    createdAt: null,
    updatedAt: "2024-07-29T15:38:42.454Z",
    sortOrder: -1,
    properties: [
      {
        idInVersion: "250202",
        id: "5d7eb185-4e39-4ee6-8aad-9b3dfb9c3c50",
        designSystemVersionId: "117328",
        name: "Token set",
        codeName: "tokenSet",
        description: "This token is part of a set",
        propertyType: "Select",
        targetElementType: "Token",
        linkElementType: null,
        options: [
          { id: "token-set-core", name: "Core", backgroundColor: "#F5F2FD" },
          {
            id: "token-set-semantic",
            name: "Semantic",
            backgroundColor: "#FEF0F5",
          },
          {
            id: "token-set-component",
            name: "Component",
            backgroundColor: "#CDFDFD",
          },
        ],
      },
    ],
    propertyValues: { tokenSet: "token-set-core" },
    value: {
      fontFamily: {
        text: "Mulish",
        referencedTokenId: "e8435484-951d-41ea-9a5f-11fbe657e6e9",
      },
      fontWeight: {
        text: "Regular",
        referencedTokenId: "0eec50c9-e1e3-4869-8cdf-a0dbd0c39e21",
      },
      fontSize: {
        unit: "Pixels",
        measure: 16,
        referencedTokenId: "e92bfa56-82cf-425d-8cbc-9343d6937c42",
      },
      textDecoration: { value: "None", referencedTokenId: null },
      textCase: { value: "Original", referencedTokenId: null },
      letterSpacing: { unit: "Pixels", measure: 0, referencedTokenId: null },
      lineHeight: {
        unit: "Pixels",
        measure: 20,
        referencedTokenId: "8a29497e-c831-454a-be11-ae4632c8867b",
      },
      paragraphIndent: { unit: "Pixels", measure: 0, referencedTokenId: null },
      paragraphSpacing: { unit: "Pixels", measure: 0, referencedTokenId: null },
      referencedTokenId: null,
    },
  },
  {
    id: "c287fffa-5bd5-4cc0-bde7-13f4a7cf6340",
    idInVersion: "12042315",
    brandId: "8e5f1a6a-9da2-4fe5-bd6b-31be14a06ccf",
    themeId: null,
    designSystemVersionId: "117328",
    name: "Footnote",
    description: "",
    tokenType: "Typography",
    origin: null,
    parentGroupId: "fbdb2c61-c9f0-471d-ac34-dcafe4e5b21f",
    createdAt: null,
    updatedAt: "2024-07-29T15:38:42.459Z",
    sortOrder: -1,
    properties: [
      {
        idInVersion: "250202",
        id: "5d7eb185-4e39-4ee6-8aad-9b3dfb9c3c50",
        designSystemVersionId: "117328",
        name: "Token set",
        codeName: "tokenSet",
        description: "This token is part of a set",
        propertyType: "Select",
        targetElementType: "Token",
        linkElementType: null,
        options: [
          { id: "token-set-core", name: "Core", backgroundColor: "#F5F2FD" },
          {
            id: "token-set-semantic",
            name: "Semantic",
            backgroundColor: "#FEF0F5",
          },
          {
            id: "token-set-component",
            name: "Component",
            backgroundColor: "#CDFDFD",
          },
        ],
      },
    ],
    propertyValues: { tokenSet: "token-set-core" },
    value: {
      fontFamily: {
        text: "Mulish",
        referencedTokenId: "e8435484-951d-41ea-9a5f-11fbe657e6e9",
      },
      fontWeight: {
        text: "Regular",
        referencedTokenId: "0eec50c9-e1e3-4869-8cdf-a0dbd0c39e21",
      },
      fontSize: {
        unit: "Pixels",
        measure: 13,
        referencedTokenId: "e69b0868-efe6-4c21-bccd-d07be885dc66",
      },
      textDecoration: { value: "None", referencedTokenId: null },
      textCase: { value: "Original", referencedTokenId: null },
      letterSpacing: { unit: "Pixels", measure: 0, referencedTokenId: null },
      lineHeight: {
        unit: "Pixels",
        measure: 20,
        referencedTokenId: "8a29497e-c831-454a-be11-ae4632c8867b",
      },
      paragraphIndent: { unit: "Pixels", measure: 0, referencedTokenId: null },
      paragraphSpacing: { unit: "Pixels", measure: 0, referencedTokenId: null },
      referencedTokenId: null,
    },
  },
  {
    id: "a0c3ab2d-b57f-4990-9ad9-bf205b7268ab",
    idInVersion: "12042318",
    brandId: "8e5f1a6a-9da2-4fe5-bd6b-31be14a06ccf",
    themeId: null,
    designSystemVersionId: "117328",
    name: "Caption",
    description: "",
    tokenType: "Typography",
    origin: null,
    parentGroupId: "fbdb2c61-c9f0-471d-ac34-dcafe4e5b21f",
    createdAt: null,
    updatedAt: "2024-07-29T15:38:42.466Z",
    sortOrder: -1,
    properties: [
      {
        idInVersion: "250202",
        id: "5d7eb185-4e39-4ee6-8aad-9b3dfb9c3c50",
        designSystemVersionId: "117328",
        name: "Token set",
        codeName: "tokenSet",
        description: "This token is part of a set",
        propertyType: "Select",
        targetElementType: "Token",
        linkElementType: null,
        options: [
          { id: "token-set-core", name: "Core", backgroundColor: "#F5F2FD" },
          {
            id: "token-set-semantic",
            name: "Semantic",
            backgroundColor: "#FEF0F5",
          },
          {
            id: "token-set-component",
            name: "Component",
            backgroundColor: "#CDFDFD",
          },
        ],
      },
    ],
    propertyValues: { tokenSet: "token-set-core" },
    value: {
      fontFamily: {
        text: "Mulish",
        referencedTokenId: "e8435484-951d-41ea-9a5f-11fbe657e6e9",
      },
      fontWeight: {
        text: "Medium",
        referencedTokenId: "a4145898-3eca-449e-aa61-a4ccdfe4482f",
      },
      fontSize: {
        unit: "Pixels",
        measure: 13,
        referencedTokenId: "e69b0868-efe6-4c21-bccd-d07be885dc66",
      },
      textDecoration: { value: "None", referencedTokenId: null },
      textCase: { value: "Original", referencedTokenId: null },
      letterSpacing: { unit: "Pixels", measure: 0, referencedTokenId: null },
      lineHeight: {
        unit: "Pixels",
        measure: 20,
        referencedTokenId: "8a29497e-c831-454a-be11-ae4632c8867b",
      },
      paragraphIndent: { unit: "Pixels", measure: 0, referencedTokenId: null },
      paragraphSpacing: { unit: "Pixels", measure: 0, referencedTokenId: null },
      referencedTokenId: null,
    },
  },
  {
    id: "c5a77b73-f38e-405f-a27d-d8542bd2b30e",
    idInVersion: "12042322",
    brandId: "8e5f1a6a-9da2-4fe5-bd6b-31be14a06ccf",
    themeId: null,
    designSystemVersionId: "117328",
    name: "Subcaption",
    description: "",
    tokenType: "Typography",
    origin: null,
    parentGroupId: "fbdb2c61-c9f0-471d-ac34-dcafe4e5b21f",
    createdAt: null,
    updatedAt: "2024-07-29T15:38:42.470Z",
    sortOrder: -1,
    properties: [
      {
        idInVersion: "250202",
        id: "5d7eb185-4e39-4ee6-8aad-9b3dfb9c3c50",
        designSystemVersionId: "117328",
        name: "Token set",
        codeName: "tokenSet",
        description: "This token is part of a set",
        propertyType: "Select",
        targetElementType: "Token",
        linkElementType: null,
        options: [
          { id: "token-set-core", name: "Core", backgroundColor: "#F5F2FD" },
          {
            id: "token-set-semantic",
            name: "Semantic",
            backgroundColor: "#FEF0F5",
          },
          {
            id: "token-set-component",
            name: "Component",
            backgroundColor: "#CDFDFD",
          },
        ],
      },
    ],
    propertyValues: { tokenSet: "token-set-core" },
    value: {
      fontFamily: {
        text: "Mulish",
        referencedTokenId: "e8435484-951d-41ea-9a5f-11fbe657e6e9",
      },
      fontWeight: {
        text: "Medium",
        referencedTokenId: "a4145898-3eca-449e-aa61-a4ccdfe4482f",
      },
      fontSize: {
        unit: "Pixels",
        measure: 10,
        referencedTokenId: "3b68c93b-561d-45e0-9cf3-bcefe154933d",
      },
      textDecoration: { value: "None", referencedTokenId: null },
      textCase: { value: "Original", referencedTokenId: null },
      letterSpacing: { unit: "Pixels", measure: 0, referencedTokenId: null },
      lineHeight: {
        unit: "Pixels",
        measure: 20,
        referencedTokenId: "8a29497e-c831-454a-be11-ae4632c8867b",
      },
      paragraphIndent: { unit: "Pixels", measure: 0, referencedTokenId: null },
      paragraphSpacing: { unit: "Pixels", measure: 0, referencedTokenId: null },
      referencedTokenId: null,
    },
  },
];
